version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "${COMPOSE_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${COMPOSE_MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${COMPOSE_MYSQL_DATABASE}"
      MYSQL_USER: "${COMPOSE_MYSQL_USER}"
      MYSQL_PASSWORD: "${COMPOSE_MYSQL_PASSWORD}"
    volumes:
      - ./mysql/data:/var/lib/mysql
